# Generated by Django 4.2 on 2024-08-14 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата')),
                ('sum', models.IntegerField(verbose_name='сумма')),
                ('way', models.CharField(choices=[('cash', 'наличными'), ('bank', 'картой')], max_length=4, verbose_name='способ')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materials.course', verbose_name='курс')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materials.lesson', verbose_name='урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
