# Generated by Django 4.2 on 2024-08-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_coursesubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='цена'),
        ),
    ]
