# Generated by Django 4.2 on 2024-08-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_course_price_lesson_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последнее обновление'),
        ),
    ]
